---
- hosts: all
  become: true
  tasks:

    - name: add docker engine repo key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg
        #state: present
        #keyserver: p80.pool.sks-keyservers.net
        #id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88D

    - name: add docker engine repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
        #state: present
        #filename: docker
        #update_cache: yes

    - name: Install list of packages
      apt:
        name: "{{ item }}"
        state: installed
        update_cache: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - docker-ce

    - name: install python-pip
      apt:
        name: python-pip
        state: present
        update_cache: yes

    - name: install docker-py
      pip:
        name: docker-py
